- name: install lazygit via go
  ansible.builtin.command:
    cmd: "go install github.com/jesseduffield/lazygit@latest"
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user }}"