dependencies:
  - { role: system_upgrade, tags: [system_upgrade] }
  - { role: version_control, tags: [version_control] }
  - { role: containers, tags: [containers] }
  - { role: k8s, tags: [k8s] }
  - { role: resterm, tags: [resterm, api] }
  - { role: bpytop, tags: [bpytop, monitoring] }
  - { role: htop, tags: [htop, monitoring] }
  - { role: eza, tags: [eza, filesystem] }
  - { role: fzf, tags: [fzf, search] }
  - { role: bat, tags: [bat, filesystem] }
  - { role: ranger, tags: [ranger, filesystem] }
  - { role: zoxide, tags: [zoxide, navigation] }