- name: install dive via go
  ansible.builtin.command:
    cmd: "go install github.com/wagoodman/dive@latest"
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user }}"