- name: install resterm via go
  ansible.builtin.command:
    cmd: "go install github.com/unkn0wn-root/resterm/cmd/resterm@latest"
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user }}"